/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Thu Aug 31 09:03:06 2017. */

#include "control-channel.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Status_fields[6] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, Status, isPowerOn, isPowerOn, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Status, coreTemp, isPowerOn, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, Status, isIDOn, coreTemp, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, Status, isManualFanControl, isIDOn, 0),
    PB_FIELD(  5, INT32   , REPEATED, CALLBACK, OTHER, Status, fanRPMs, isManualFanControl, 0),
    PB_LAST_FIELD
};

const pb_field_t Hello_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Hello, version, version, 0),
    PB_LAST_FIELD
};

const pb_field_t Event_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Event, type, type, 0),
    PB_LAST_FIELD
};

const pb_field_t Command_fields[5] = {
    PB_ONEOF_FIELD(command,   1, MESSAGE , ONEOF, STATIC  , FIRST, Command, noCommand, noCommand, &Command_NoCommand_fields),
    PB_ONEOF_FIELD(command,   2, MESSAGE , ONEOF, STATIC  , UNION, Command, idCommand, idCommand, &Command_IDCommand_fields),
    PB_ONEOF_FIELD(command,   3, MESSAGE , ONEOF, STATIC  , UNION, Command, powerCommand, powerCommand, &Command_PowerCommand_fields),
    PB_ONEOF_FIELD(command,   4, MESSAGE , ONEOF, STATIC  , UNION, Command, fanCommand, fanCommand, &Command_FanCommand_fields),
    PB_LAST_FIELD
};

const pb_field_t Command_NoCommand_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Command_NoCommand, dummy, dummy, 0),
    PB_LAST_FIELD
};

const pb_field_t Command_IDCommand_fields[2] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, Command_IDCommand, on, on, 0),
    PB_LAST_FIELD
};

const pb_field_t Command_PowerCommand_fields[2] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Command_PowerCommand, op, op, 0),
    PB_LAST_FIELD
};

const pb_field_t Command_FanCommand_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Command_FanCommand, op, op, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Command_FanCommand, whichFan, op, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Command_FanCommand, dutyCycle, whichFan, 0),
    PB_LAST_FIELD
};

const pb_field_t Sol_fields[2] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Sol, portNum, portNum, 0),
    PB_LAST_FIELD
};





/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, command.noCommand) < 65536 && pb_membersize(Command, command.idCommand) < 65536 && pb_membersize(Command, command.powerCommand) < 65536 && pb_membersize(Command, command.fanCommand) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Status_Hello_Event_Command_Command_NoCommand_Command_IDCommand_Command_PowerCommand_Command_FanCommand_Sol)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Command, command.noCommand) < 256 && pb_membersize(Command, command.idCommand) < 256 && pb_membersize(Command, command.powerCommand) < 256 && pb_membersize(Command, command.fanCommand) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Status_Hello_Event_Command_Command_NoCommand_Command_IDCommand_Command_PowerCommand_Command_FanCommand_Sol)
#endif


/* @@protoc_insertion_point(eof) */
